ALTER TABLE bills ADD COLUMN sort_order INTEGER NOT NULL DEFAULT 0;
ALTER TABLE financial_accounts ADD COLUMN sort_order INTEGER NOT NULL DEFAULT 0;
ALTER TABLE household_tasks ADD COLUMN sort_order INTEGER NOT NULL DEFAULT 0;
ALTER TABLE shopping_items ADD COLUMN sort_order INTEGER NOT NULL DEFAULT 0;
